baseURL = "theharold9000.github.io"
languageCode = "en-us"
title = "Harold Liu"
theme = "hyde-hyde"

[params]
    description = "Thoughts & Things"
    postNavigation = false
    layoutReverse = true
    themeColor = "theme-base-0d"

[params.social]
    github = "theharold9000"
    linkedin = "harold-liu"
    twitter = "theharold9000"

[[memu.main]]
    name = "Posts"
    url = "/posts/"

[[memu.main]]
    name = "About Me"
    url = "/about/about-me"