baseURL = "theharold9000.github.io"
languageCode = "en-us"
title = "Harold Liu"
theme = "hyde-hyde"

[params]
    description = "Thoughts & Things"

[params.social]
    github = "theharold9000"
    linkedin = "harold-liu"
    twitter = "theharold9000"

[Menus]
    main = [
        {Name = "LinkedIn", URL = "https://www.linkedin.com/in/harold-liu/"},
        {Name = "Twitter", URL = "https://twitter.com/theharold9000"},
    ]