baseURL = "theharold9000.github.io"
languageCode = "en-us"
title = "Harold's Blog"
theme = "hyde-hyde"

[params]
    description = "I'm a 26 yeard old technical recruiter living in Brisbane, Australia. These are my thought"

[Menus]
    main = [
        {Name = "LinkedIn", URL = "https://www.linkedin.com/in/harold-liu/"},
        {Name = "Twitter", URL = "https://twitter.com/theharold9000"},
    ]